[versions]
slf4j-api = "2.0.7"
logback = "1.4.6"
commons-math = "3.6.1"
fits = "1.17.1"
gson = "2.10.1"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
commons-math = { module = "org.apache.commons:commons-math3", version.ref = "commons-math" }
fits = { module = "gov.nasa.gsfc.heasarc:nom-tam-fits", version.ref = "fits" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
