name: Distributions and installers

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
            version: '22.3.0'
            java-version: '17'
            components: 'native-image'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            native-image-job-reports: 'true'
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew jpackage

      - name: Build native binary
        run: ./gradlew nativeCompile

      - uses: actions/upload-artifact@v3
        with:
          name: SER Player Native ${{ matrix.os }} binary (experimental)
          path: "ser-player/build/native/nativeCompile"
      - uses: actions/upload-artifact@v3
        with:
          name: JSol'Ex Native ${{ matrix.os }} binary (experimental)
          path: "jsolex/build/native/nativeCompile"

      - uses: actions/upload-artifact@v3
        with:
          name: SER Player ${{ matrix.os }} installer
          path: "ser-player/build/jpackage"
      - uses: actions/upload-artifact@v3
        with:
          name: JSol'Ex ${{ matrix.os }} installer
          path: "ser-player/build/jpackage"
