name: Main

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
            version: '22.3.0'
            java-version: '17'
            components: 'native-image'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            native-image-job-reports: 'true'
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build distZip distTar

      - name: Build native binary
        run: ./gradlew nativeCompile

      - uses: actions/upload-artifact@v3
        with:
          name: Distribution Zips
          path: "**/build/distributions/*.zip"
      - uses: actions/upload-artifact@v3
        with:
          name: Distribution Tarballs
          path: "**/build/distributions/*.tar.gz"
      - uses: actions/upload-artifact@v3
        with:
          name: Native ${{ matrix.os }} binary
          path: "**/build/native/nativeCompile"
